global:
  scrape_interval:     60s
  scrape_timeout:      10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s
    scrape_timeout:  1s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus


  - job_name: grafana
    scrape_interval: 5s
    scrape_timeout:  4s
    static_configs:
      - targets: ['localhost:3000']
        labels:
          instance: pmm-server


  - job_name: linux
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['linux:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'

    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: pmm-server


  - job_name: proxysql
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['proxysql:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mongodb
    scrape_interval: 1s
    scrape_timeout:  1s
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mongodb:metrics']

    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,cluster_([-\w:\.]+),.*'
      target_label:  'cluster'
      replacement:   '$1'


  - job_name: mysql-hr
    scrape_interval: 1s
    scrape_timeout:  1s
    params:
      collect[]:
        - 'global_status'
        - 'info_schema.innodb_metrics'
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mysql-mr
    scrape_interval: 5s
    scrape_timeout:  1s
    params:
      collect[]:
        - 'slave_status'
        - 'info_schema.processlist'
        - 'perf_schema.eventswaits'
        - 'perf_schema.file_events'
        - 'perf_schema.tablelocks'
        - 'info_schema.query_response_time'
        - 'engine_innodb_status'
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'


  - job_name: mysql-lr
    scrape_interval: 60s
    scrape_timeout:   5s
    params:
      collect[]:
        - 'global_variables'
        - 'info_schema.tables'
        - 'auto_increment.columns'
        - 'binlog_size'
        - 'perf_schema.tableiowaits'
        - 'perf_schema.indexiowaits'
        - 'perf_schema.file_instances'
        - 'info_schema.userstats'
        - 'info_schema.tablestats'
        - 'perf_schema.eventsstatements'
        - 'info_schema.clientstats'
        - 'info_schema.innodb_tablespaces'
        - 'engine_tokudb_status'
        - 'heartbeat'
    basic_auth:
      username: ENV_SERVER_USER
      password: ENV_SERVER_PASSWORD

    tls_config:
      insecure_skip_verify: true

    consul_sd_configs:
    - server:   'localhost:8500'
      datacenter: dc1
      services: ['mysql:metrics']

    relabel_configs:
    - target_label:  'job'
      replacement:   'mysql'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,alias_([-\w:\.]+),.*'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,scheme_https,.*'
      target_label:  '__scheme__'
      replacement:   'https'
